// This file was generated by counterfeiter
// counterfeiter -o ios/iuser/user_fake.go --fake-name Fake ios/iuser/user.go User

package iuser

import (
	"os/user"
	"sync"
)

//Fake ...
type Fake struct {
	LookupStub        func(string) (*user.User, error)
	lookupMutex       sync.RWMutex
	lookupArgsForCall []struct {
		arg1 string
	}
	lookupReturns struct {
		result1 *user.User
		result2 error
	}
	LookupGroupStub        func(string) (*user.Group, error)
	lookupGroupMutex       sync.RWMutex
	lookupGroupArgsForCall []struct {
		arg1 string
	}
	lookupGroupReturns struct {
		result1 *user.Group
		result2 error
	}
	CurrentStub        func() (*user.User, error)
	currentMutex       sync.RWMutex
	currentArgsForCall []struct{}
	currentReturns     struct {
		result1 *user.User
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

//NewFake is the preferred way to initialise a Fake
func NewFake() *Fake {
	return new(Fake)
}

//Lookup ...
func (fake *Fake) Lookup(arg1 string) (*user.User, error) {
	fake.lookupMutex.Lock()
	fake.lookupArgsForCall = append(fake.lookupArgsForCall, struct {
		arg1 string
	}{arg1})
	fake.recordInvocation("Lookup", []interface{}{arg1})
	fake.lookupMutex.Unlock()
	if fake.LookupStub != nil {
		return fake.LookupStub(arg1)
	}
	return fake.lookupReturns.result1, fake.lookupReturns.result2
}

//LookupCallCount ...
func (fake *Fake) LookupCallCount() int {
	fake.lookupMutex.RLock()
	defer fake.lookupMutex.RUnlock()
	return len(fake.lookupArgsForCall)
}

//LookupArgsForCall ...
func (fake *Fake) LookupArgsForCall(i int) string {
	fake.lookupMutex.RLock()
	defer fake.lookupMutex.RUnlock()
	return fake.lookupArgsForCall[i].arg1
}

//LookupReturns ...
func (fake *Fake) LookupReturns(result1 *user.User, result2 error) {
	fake.LookupStub = nil
	fake.lookupReturns = struct {
		result1 *user.User
		result2 error
	}{result1, result2}
}

//LookupGroup ...
func (fake *Fake) LookupGroup(arg1 string) (*user.Group, error) {
	fake.lookupGroupMutex.Lock()
	fake.lookupGroupArgsForCall = append(fake.lookupGroupArgsForCall, struct {
		arg1 string
	}{arg1})
	fake.recordInvocation("LookupGroup", []interface{}{arg1})
	fake.lookupGroupMutex.Unlock()
	if fake.LookupGroupStub != nil {
		return fake.LookupGroupStub(arg1)
	}
	return fake.lookupGroupReturns.result1, fake.lookupGroupReturns.result2
}

//LookupGroupCallCount ...
func (fake *Fake) LookupGroupCallCount() int {
	fake.lookupGroupMutex.RLock()
	defer fake.lookupGroupMutex.RUnlock()
	return len(fake.lookupGroupArgsForCall)
}

//LookupGroupArgsForCall ...
func (fake *Fake) LookupGroupArgsForCall(i int) string {
	fake.lookupGroupMutex.RLock()
	defer fake.lookupGroupMutex.RUnlock()
	return fake.lookupGroupArgsForCall[i].arg1
}

//LookupGroupReturns ...
func (fake *Fake) LookupGroupReturns(result1 *user.Group, result2 error) {
	fake.LookupGroupStub = nil
	fake.lookupGroupReturns = struct {
		result1 *user.Group
		result2 error
	}{result1, result2}
}

//Current ...
func (fake *Fake) Current() (*user.User, error) {
	fake.currentMutex.Lock()
	fake.currentArgsForCall = append(fake.currentArgsForCall, struct{}{})
	fake.recordInvocation("Current", []interface{}{})
	fake.currentMutex.Unlock()
	if fake.CurrentStub != nil {
		return fake.CurrentStub()
	}
	return fake.currentReturns.result1, fake.currentReturns.result2
}

//CurrentCallCount ...
func (fake *Fake) CurrentCallCount() int {
	fake.currentMutex.RLock()
	defer fake.currentMutex.RUnlock()
	return len(fake.currentArgsForCall)
}

//CurrentReturns ...
func (fake *Fake) CurrentReturns(result1 *user.User, result2 error) {
	fake.CurrentStub = nil
	fake.currentReturns = struct {
		result1 *user.User
		result2 error
	}{result1, result2}
}

//Invocations ...
func (fake *Fake) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.lookupMutex.RLock()
	defer fake.lookupMutex.RUnlock()
	fake.lookupGroupMutex.RLock()
	defer fake.lookupGroupMutex.RUnlock()
	fake.currentMutex.RLock()
	defer fake.currentMutex.RUnlock()
	return fake.invocations
}

func (fake *Fake) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ User = new(Fake)
